In [2]:
#1.a
import numpy as np

# Creating random vector of size 15 with integers in the range 1-20
vec = np.random.randint(low=1, high=21, size=15)

# Reshaping the vector to 3x5 array
arr = vec.reshape(3, 5)

# Printing the array shape
print("Array shape:", arr.shape)

# Replacing max in each row with 0
arr[np.arange(len(arr)), np.argmax(arr, axis=1)] = 0

# Creating a 4x3 array of 4-byte integers
arr_2d = np.zeros((4, 3), dtype=np.int32)

# Printing the shape, type and data type of the array
print("Array shape:", arr_2d.shape)
print("Array type:", type(arr_2d))
print("Array data type:", arr_2d.dtype)

Array shape: (3, 5)
Array shape: (4, 3)
Array type: <class 'numpy.ndarray'>
Array data type: int32


In [6]:
# 1.b
# Defining the square array
arr = np.array([[3, -2], [1, 0]])

# Computing the eigenvalues and right eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(arr)

# Printing the eigenvalues and right eigenvectors
print("Eigenvalues:", eigenvalues)
print("Right Eigenvectors:\n", eigenvectors)


Eigenvalues: [2. 1.]
Right Eigenvectors:
 [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


In [7]:
# 1.c
# Defining the given array
arr = np.array([[0, 1, 2], [3, 4, 5]])

# Computing the sum of the diagonal elements
diag_sum = np.trace(arr)

# Printing the sum of the diagonal elements
print("Sum of diagonal elements:", diag_sum)


Sum of diagonal elements: 4


In [12]:
# 1.d
# Define the array
arr = np.array([[1, 2], [3, 4], [5, 6]])

# Reshape the array to 2x3
arr_2x3 = np.reshape(arr, (2, 3))

# Reshape the array back to 3x2
arr_3x2 = np.reshape(arr_2x3, (3, 2))

# Print the original array and the reshaped arrays
print("Original Array:\n", arr)
print("Reshaped Array (2x3):\n", arr_2x3)
print("Reshaped Array (3x2):\n", arr_3x2)

Original Array:
 [[1 2]
 [3 4]
 [5 6]]
Reshaped Array (2x3):
 [[1 2 3]
 [4 5 6]]
Reshaped Array (3x2):
 [[1 2]
 [3 4]
 [5 6]]
